name: Run Bundlewatch

on:
  workflow_call:
    secrets:
      bundlewatch_token:
        required: true

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - run: npm i
      - run: npm run build
      - run: npm run bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.bundlewatch_token }}
