name: Test Template

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: "ubuntu-latest"
      python-version:
        type: string
        required: false
        default: "3.9"
      tasting-dir:
        type: string
        required: false
        default: ".tasting"
      cc-options:
        type: string
        required: false
        default: ""
      pkg-dir:
        type: string
        required: false
        default: "my-package"
      command-dir:
        type: string
        required: false
        default: ""
      command:
        type: string
        required: false
        default: "pytest"

jobs:
  upgrade:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - uses: snok/install-poetry@v1

      - run: poetry install
      - run: mkdir -p ${{ inputs.tasting-dir }}
      - name: Generate a project
        working-directory: ${{ inputs.tasting-dir }}
        run: poetry run cookiecutter ../ --no-input --overwrite-if-exists ${{ inputs.cc-options }}

      - name: Install generated project deps
        working-directory: ${{ inputs.tasting-dir }}/${{ inputs.pkg-dir }}/${{ inputs.command-dir }}
        run: poetry install -E docs
      - name: Run Test
        working-directory: ${{ inputs.tasting-dir }}/${{ inputs.pkg-dir }}
        run: poetry run ${{ inputs.command }}
