name: CI for Gatsby site

on:
  workflow_call:
    secrets:
      bundlewatch_token:
        required: true

jobs:
  lint:
    strategy:
      matrix:
        linter:
          - eslint
          - prettier
          - tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run lint:${{ matrix.linter }}

  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build
      - run: npm run bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.bundlewatch_token }}
