name: Upgrade dependencies

on:
  workflow_call:
    secrets:
      gh_pat:
        required: true

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - run: npm i
      - run: npm upgrade
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.gh_pat }}
          branch: update/npm-upgrade
          title: "chore(deps): run npm upgrade"
          commit-message: "chore(deps): run npm upgrade"
