name: Upgrade dependencies

on:
  workflow_call:
    secrets:
      github_token:
        required: true

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - run: npm i
      - run: npm upgrade
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.github_token }}
          branch: update/npm-upgrade
          title: Upgrade dependencies
          commit-message: "chore(deps): Run npm upgrade"
