name: Upgrade dependencies

on:
  workflow_call:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - run: npm i
      - run: npm upgrade
